language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
branches:
  only:
    - master
services: redis-server
cache: pip
install: pip install -r requirements-dev.txt
script: coverage run -m pytest -v
after_success:
  - codecov -t {{CODECOV_TOKEN}}
